name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_epub_viewer:
    path: ../
  cupertino_icons: ^1.0.6
  screen_brightness: ^1.0.1
  file_picker: ^8.1.2
  path_provider: ^2.1.3
  share_plus: ^11.0.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/

  fonts:
    #book fonts
    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf

    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
