name: flutter_epub_viewer
description: "A Flutter package for viewing Epub documents developed by combining the power of Epubjs and flutter_inappwebview"
version: 1.2.8
homepage: https://github.com/fayis672/epub_viewer

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.3.0
  json_annotation: ^4.9.0

platforms:
  android:
  ios:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/webpage/dist/
    - lib/assets/webpage/html/
    - lib/assets/fonts/

  fonts:
    - family: NewYork
      fonts:
        - asset: lib/assets/fonts/NewYork.ttf
    - family: SFPro
      fonts:
        - asset: lib/assets/fonts/SF-Pro.ttf
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/Gilroy-Medium.ttf
