name: flutter_epub_viewer
description: "A Flutter package for viewing Epub documents developed by combining the power of Epubjs and flutter_inappwebview"
version: 1.2.8
homepage: https://github.com/fayis672/epub_viewer

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.3.0
  json_annotation: ^4.10.0

platforms:
  android:
  ios:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/webpage/dist/
    - lib/assets/webpage/html/
    - lib/assets/fonts/

  fonts:
    - family: NewYork
      fonts:
        - asset: lib/assets/fonts/NewYork.ttf
    - family: SFPro
      fonts:
        - asset: lib/assets/fonts/SF-Pro.ttf
    - family: Alegreya
      fonts:
        - asset: lib/assets/fonts/Alegreya.ttf
    - family: Amazon Ember
      fonts:
        - asset: lib/assets/fonts/Amazon-Ember-Regular.ttf
    - family: Atkinson Hyperlegible
      fonts:
        - asset: lib/assets/fonts/AtkinsonHyperlegible-Regular.ttf
    - family: Bitter Pro
      fonts:
        - asset: lib/assets/fonts/BitterPro-Regular.ttf
    - family: Bookerly
      fonts:
        - asset: lib/assets/fonts/Bookerly.ttf
    - family: Droid Sans
      fonts:
        - asset: lib/assets/fonts/DroidSans.ttf
    - family: EB Garamond
      fonts:
        - asset: lib/assets/fonts/EBGaramond-Var.ttf
    - family: Gentium Book Plus
      fonts:
        - asset: lib/assets/fonts/GentiumBookPlus-Regular.ttf
    - family: Halant
      fonts:
        - asset: lib/assets/fonts/Halant-Regular.ttf
    - family: IBM Plex Sans
      fonts:
        - asset: lib/assets/fonts/IBMPlexSans-Regular.ttf
    - family: LinLibertine
      fonts:
        - asset: lib/assets/fonts/LinLibertine-Regular.ttf
    - family: Literata
      fonts:
        - asset: lib/assets/fonts/Literata-Var.ttf
    - family: Lora
      fonts:
        - asset: lib/assets/fonts/Lora-Var.ttf
    - family: Ubuntu
      fonts:
        - asset: lib/assets/fonts/Ubuntu-Var.ttf
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/Gilroy-Medium.ttf
